# Keyboard event map
#
# Key names are from directinput
# https://learn.microsoft.com/en-us/previous-versions/windows/desktop/ee418641(v=vs.85)
# without the DIK_ prefix
#
# Mouse is LMB or RMB
#
# Events are specicified like this:
# ```toml
# [[InputEvent]]
# name = "SomeKeyEvent"
# keys = [ "A", "B", "LMB" ]
# exclusive = false
# duration = 0.0
# trigger = "once"
# ```
#
# - name: Is the event name. This determines what is done when these keys are
#         pressed. More that one `[[InputEvent]]` can trigger the same event name
#         which means you can have multiple keys combinations do that same thing
#         if you repeat the name
# - keys: Is a comma seperated list [] of keys names that will trigger the event
# - exclusive: When true means ONLY these keys must be pressed for the entire duration
#             when false other keys may be pressed and the event will still fire
# - duration: The length of time the keys must be pressed for before they fire
# - trigger: Either "once or "continuous". If "once" the keys must be released
#            before the event will fire again. If "continuous" the event will
#            fire every frame until the keys are released

# !!! If you will forget to put , between "key" "key" - controls will break and input won't work:             !!!
# !!! Correct: keys = ["Key","Key"]. INCORRECT: keys = ["Key""Key"]                                           !!!

#========================================================
#================ V O R E
#========================================================

[[InputEvent]]
name = "Vore"
keys = [ "LSHIFT", "V"]
trigger = "once"

# Start Vore Attempt. Requires 'Vore' perk!

#========================================================
#================ S T O M P S
#========================================================
[[InputEvent]]
name = "RightStomp_Strong"
keys = ["LSHIFT", "E", "LMB"]

[[InputEvent]]
name = "LeftStomp_Strong"
keys = ["LSHIFT", "Q", "LMB"]

# ^ Trigger powerful stomps. All stomps REQUIRE 'Destruction Basics' perk!


[[InputEvent]]
name = "RightStomp"
keys = ["LSHIFT", "E"]
duration = 0.33

# Trigger Stomp Right animation. All stomps REQUIRE 'Destruction Basics' perk!

[[InputEvent]]
name = "LeftStomp"
keys = ["LSHIFT", "Q"]
duration = 0.33

# Trigger Stomp Left animation. All stomps REQUIRE 'Destruction Basics' perk!

#========================================================
#================ T H I G H  C R U S H
#========================================================

[[InputEvent]]
name = "ThighCrush"
keys = ["LALT"]
exclusive = true
duration = 2.0

# Enter Thigh Crush Animation. Requires 'Killer Thighs' perk!

[[InputEvent]]
name = "ThighCrushKill"
keys = ["LMB"]
exclusive = false

# Start Leg Spread, Leg Close animation. Requires 'Killer Thighs' perk!

[[InputEvent]]
name = "ThighCrushSpare"
keys = ["RMB"]
exclusive = false

[[InputEvent]]
name = "ThighCrushSpare"
keys = ["LSHIFT", "W"]
exclusive = true

# ^ Ways to Exit Thigh Crush animation. Requires 'Killer Thighs' perk!

#========================================================
#============ T H I G H  S A N D W I C H
#========================================================

[[InputEvent]]
name = "ThighSandwichEnter"
keys = ["LSHIFT", "C"]
exclusive = true

# Attempt to Start Thigh Sandwich animation with someone. Requires 'Killer Thighs' perk!

[[InputEvent]]
name = "ThighSandwichAttackHeavy"
keys = ["LMB", "RMB"]
exclusive = false
trigger = "continuous"

# Do Heavy Thigh Sandwich attack, Can be Looped. Requires 'Killer Thighs' perk!

[[InputEvent]]
name = "ThighSandwichAttack" 
keys = ["LMB"]
exclusive = false
trigger = "continuous"

# Do Thigh Sandwich attack, Can be Looped. Requires 'Killer Thighs' perk!


[[InputEvent]]
name = "ThighSandwichExit"
keys = ["RMB"]
exclusive = true
duration = 0.8

[[InputEvent]]
name = "ThighSandwichExit"
keys = ["LSHIFT", "W"]
exclusive = true

# ^ Ways to exit Thigh Sandwich.  Requires 'Killer Thighs' perk!

#========================================================
#========================= G R A B
#========================================================

[[InputEvent]]
name = "Grab"
keys = ["F"]
duration = 10.0 
# Grabs nearby actor. It is currently a bit buggy, has no Animations and is pretty much WIP, so use it at your own risk. 
# Requires 'Destruction Basics' perk!

[[InputEvent]]
name = "GrabKill"
keys = ["LMB"]
exclusive = false
trigger = "continuous"

# Damage actor that is currently held in hand
# Crushes actor if there's no health left.

[[InputEvent]]
name = "GrabSpare"
keys = ["RMB"]
exclusive = false

# Release actor from hand.

#========================================================
#========================= C A M E R A
#========================================================

[[InputEvent]]
name = "HorizontalCameraReset"
keys = ["RIGHT", "LEFT"]
exclusive = false
trigger = "continuous"

[[InputEvent]]
name = "VerticalCameraReset"
keys = ["UP", "DOWN"]
exclusive = false
trigger = "continuous"

[[InputEvent]]
name = "CameraLeft"
keys = ["LALT", "LEFT"]
exclusive = false
trigger = "continuous"

[[InputEvent]]
name = "CameraRight"
keys = ["LALT", "RIGHT"]
exclusive = false
trigger = "continuous"

[[InputEvent]]
name = "CameraUp"
keys = ["LALT", "UP"]
exclusive = true
trigger = "continuous"

[[InputEvent]]
name = "CameraDown"
keys = ["LALT", "DOWN"]
exclusive = false
trigger = "continuous"

#========================================================
#========================= A N I M  S P E E D
#========================================================

[[InputEvent]]
name = "AnimSpeedUp"
keys = ["LMB"]
exclusive = false
trigger = "continuous"

# Boost animation speed of Stomp/Thigh Crush/Thigh Sandwich. Can be applied only during specific events that allow it.

[[InputEvent]]
name = "AnimSpeedDown"
keys = ["RMB"]
exclusive = true
trigger = "continuous"

# Slow down animation speed of Stomp/Thigh Crush/Thigh Sandwich. Can be applied only during specific events that allow it.

[[InputEvent]]
name = "AnimMaxSpeed"
keys = ["RMB", "LMB"]
exclusive = false
trigger = "continuous"

# Massively Boost animation speed of Stomp/Thigh Crush/Thigh Sandwich. Can be applied only during specific events that allow it.

#========================================================
#========================= P E R K S
#========================================================

#=========================Size Reserve

[[InputEvent]]
name = "SizeReserve"
keys = ["E"]
duration = 1.2
trigger = "continuous"

# Use size reserve and grow yourself. Requires Perk.

[[InputEvent]]
name = "DisplaySizeReserve"
keys = ["F"]
duration = 1.2

# Hold to print size reserve value. Requires Perk.

#=========================Total Control

[[InputEvent]]
name = "TotalControlGrow"
keys = ["UP", "LEFT"]
exclusive = false
trigger = "continuous"

# Grow self. Requires Matching Perk.

[[InputEvent]]
name = "TotalControlShrink"
keys = ["DOWN", "LEFT"]
exclusive = false
trigger = "continuous" 

# Shrink self. Requires Matching Perk.

[[InputEvent]]
name = "TotalControlGrowOther"
keys = ["LSHIFT", "UP", "LEFT"]
exclusive = false
trigger = "continuous"

# Grow followers. Requires Matching Perk.

[[InputEvent]]
name = "TotalControlShrinkOther"
keys = ["LSHIFT", "DOWN", "LEFT"]
exclusive = false
trigger = "continuous"

# Shrink followers. Requires Matching Perk.

#========================================================
#========================= M I S C
#========================================================

[[InputEvent]]
name = "PartyReport"
keys = ["LCONTROL"]
duration = 1.2

# Reports Follower's size info into the console